[app]
host = "127.0.0.1"
port = 8080
data_source = "mysql"

[log]
log_level = "info"
log_dir = "logs"
log_name = "app.log"

[data_source.mysql]
url = "mysql://user:pass@host:port/db"

[data_source.etcd]
endpoints = ["http://localhost:2379"]
username = "root"
password = "pwd"
