[workspace]
members = ["mcp-axum", "mcp-macro", "mcp-core", "mcp-common", "mcp-plugin"]

[workspace.dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
    "fmt",
    "json",
] }
tracing-appender = "0.2.3"
